version : '3'
services:
  redis:
    image: 'redis:latest'
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./api
    depends_on:
      - redis
    volumes:
      - ./api:/app
    environment:
      - PORT=3050
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - '3050:3050' 
